# Generated by Django 3.2.6 on 2021-11-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20211109_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='firstname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='lastname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
