# Generated by Django 3.2.6 on 2021-10-27 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0003_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brandname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eboutique.brand'),
        ),
    ]
