# Generated by Django 3.2.6 on 2021-10-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0006_auto_20211028_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
