# Generated by Django 3.2.6 on 2021-10-28 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0007_alter_review_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
