# Generated by Django 3.2.6 on 2021-10-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0011_product_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eboutique.review'),
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
