# Generated by Django 3.2.6 on 2021-10-28 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0014_remove_product_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='eboutique.review'),
        ),
    ]
