# Generated by Django 3.2.6 on 2021-10-28 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0016_auto_20211028_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='message',
        ),
    ]
