# Generated by Django 3.2.6 on 2021-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0017_remove_product_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
