# Generated by Django 3.2.6 on 2021-10-28 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0019_message_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='review',
        ),
    ]
