# Generated by Django 3.2.6 on 2021-10-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0020_rename_message_message_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eboutique.product'),
        ),
    ]
