# Generated by Django 3.2.6 on 2021-10-28 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0021_alter_message_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='review',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
