# Generated by Django 3.2.6 on 2021-11-10 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eboutique', '0023_auto_20211103_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
